version: 2
jobs:
  build:
    working_directory: ~/project
    environment:
      CI: true
    machine:
      node:
        version: 9.2.1
    steps:
      - checkout
      - run: yarn
      - run: yarn test -t src

dependencies:
  override:
    - yarn
test:
  override:
    - yarn test

workflows:
  version: 2
  frontend:
    jobs:
      - build
